<table>
    <thead>
    <tr>
        <th>first_name</th>
        <th>middle_name</th>
        <th>last_name</th>
        <th>email</th>
        <th>gender</th>
        <th>date_of_birth</th>
        <th>phone_number</th>
        <th>address</th>
        <th>profession</th>

    </tr>
    </thead>
    <tbody>
         <tr>
            <td>Ahmad</td>
            <td>Ali</td>
            <td>Umar</td>
            <td>aau@abc.com</td>
            <td>Male</td>            
            <td>1980-08-03</td>
            <td>08012345679</td>
            <td>Katsina</td>
            <td>Trader</td>
         </tr>
    </tbody>
</table>